### PR TITLE
Updated german ability, keyword, set and type CSVS

### PR DESCRIPTION
**Pull request by Mofte**
Updated the CSVS ability.csv, keyword.csv and type.csv to include all new and corrected official translations up to OUT and 2HP.
Added 2HP to set.csv, Unique ID for 2HP needs to be generated. 
artists.csv wasn't updated as there are no artworks/artists specific to the german localisation.

### CODE REVIEW

**Comment by nathaneastwood** [comment]
This is 🔥

**Comment by luceleaftea** [comment]
This is *incredible*, thank you so much @Mofte!! I'm going to be working on putting out a new data set release tonight, and then will take a look at this PR more in depth afterwards! 😄

**Comment by Mofte** [comment]
Nah, nothing big, just a bunch of copy & paste. Hope it's correct and I didn't mess up anything. 
If it's fine I could probably do the other European languages as well even though I only speak very basic French and hardly any Spanish/Italian but it'd mostly be copy&paste as well.

**Comment by luceleaftea** [comment]
Looks great - pulling it in and I'll generate a new id for HP2!

**Pull request merged**
