### PR TITLE
 Remove reminder text from all functional text #199

### PR DESCRIPTION
**Pull request by PvtVoid**
Should be done for all English cards.ods

### CODE REVIEW

**Comment by luceleaftea** [comment]
Hey! Would you be willing to export the ODS file to the english CSV as well? That makes it easier to review from here and solve merge conflicts on my end :D 

Also, the ~$card.ods file should not be commited. I should probably make an update to the .gitignore to help with that 😅 

Thank you for the PR!!

**Comment by PvtVoid** [comment]
Should be done now!

**Comment by luceleaftea** [comment]
Thanks for the update! A quick glance seems to show most of the reminder text is indeed removed, but sadly something in the export seems to have reorganized all the CSV lines :( The order should be maintained across updates so that git diffs are easily comparable. Do you know if there's an easy way to sort them back to how it was? The sort order was promos not in sets, followed by cards in sets in order of their release.

**Comment by PvtVoid** [comment]
The order should be fixed back to develop order! 🙌🏼

**Comment by luceleaftea** [comment]
The CSVs are looking better, thank you! Something happened with the flavor text though - some of them were split into multiple columns, which shifted the rest of the columns in those rows over. There are also some merge conflicts. If it would be easier, I could always copy/paste the column you edited into develop and credit you in the changelog? 🤔 That way you don't have to deal with that nightmare merge commit 😅

**Comment by PvtVoid** [comment]
Yes please do! 🙏

**Comment by luceleaftea** [comment]
Pulled the data in - thank you!!

**Pull request closed without merging**
